### ISSUE TITLE
[BUG] XP text looks funky when window is in a vertical aspect ratio

### ISSUE THREAD

**Issue by Aethergarden** [Founntain/osuplayer-issues#20]
**Your osu!player username**
Magi

**Describe the bug**
When the player is in a vertical aspect ratio, the XP text seems to overlap and look funky.

**To Reproduce**
1. Open osu!player plus
2. Strech the window to a vertical aspect ratio (i.e. 1080x1920)
3. The text in the "You" area can overlap and look weird.

**Expected behavior**
A clear and concise description of what you expected to happen:|
Text does not overlap and you are able to view how much XP is needed to progress to the next level.

**Screenshots**
If applicable, add screenshots to help explain your problem:
https://this-is-an-extremely.questionable.link/ievUrK

**Additional context**
Add any other context about the problem here:
Latest version at time of submission

**Comment by Founntain** [comment]
I thought this is already fixed.

**Comment by Founntain** [comment]
Fixed in Version **2021.527.1229.42**

**Comment by Aethergarden** [comment]
Still occurs in 2021.528.1458.51

https://this-is-an-extremely.questionable.link/6J4UC4

**Comment by Founntain** [comment]
Please update your English.lang by deleting or redownloading it via the language manager.

**Comment by Aethergarden** [comment]
This fixed it, thanks
